sphinx-contrib/matlabdomain

- .gitignore
- .travis.yml
- setup.py
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- sphinxcontrib/matlab.py
- tests/test_docs/conf.py
- tests/test_mat_types.py
- tests/test_matlabify.py
- tox.ini
- I ran 2to3.py and added from __future__ imports. So now its Python 2.7 and 3.6 compatible
- Setup travis to run the tests and generate html from the docs.
- Fixed the Sphinx <1.4.3 warning on "WARNING: 4 column based index found"
- Issues:
- Still has warnings like "WARNING: while setting up extension sphinxcontrib.matlab: directive 'automodule' is already registered, it will be overridden"
> Py 2.7/3.6 compatible, enable travis, Sphinx >= 1.4.3

- sphinxcontrib/mat_types.py
Copy of https://bitbucket.org/bwanamarko/sphinxcontrib-matlabdomain/pull-requests/5/better-exception-when-input-args-contains/diff
> better exception, when input args contains "..."

- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithCommentHeader.m
- tests/test_data/f_with_comment_header.m
- tests/test_data/script_with_comment_header.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
I have added a simple function that removes any comment lines at the begin of current read code string.
> Bug fix for issue #58, when a Matlab-file has some comment lines at the top.

- sphinxcontrib/mat_documenters.py
- sphinxcontrib/matlab.py
Builds are failing for me with Sphinx 1.7.0. These changes resolve the incompatibilities.
> Dependency fix for Sphinx 1.7.

- README.rst
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- sphinxcontrib/matlab.py
- tests/test_data/f_with_latin_1.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
Hi !
I tried using your tool for our projects and I had some problems for non UTF-8 files (parser would crash on autodoc parsing).
I made the following changes to handle it :
- Added default behavior to replace errors with ? chars
- Added sphinx configuration to choose parsing encoding (default = UTF-8)
I added the corresponding unit test and documentation.
Please tell me if you have any remarks regarding this pull request.
> Fix autodoc parsing error when source matlab file is not encoded as UTF-8

- CHANGES.rst
- sphinxcontrib/mat_lexer.py
- tests/test_data/ClassWithStrings.m
- tests/test_docs/index.rst
- tests/test_lexer.py
- tests/test_matlabify.py
- tests/test_parse_mfile.py
Fixed #103 
If a double quoted string was followed by a single quoted string, the lexer
would produce incorrect token, causing the a parser warning. Fixed by merging
parts from pygments.
> Bug 103 fixed

- tests/test_autodoc.py
- tests/test_package_links.py
- tests/test_package_prefix.py
- tests/test_pymat.py
- tests/test_pymat_common_root.py
* Sphinx 3.1.1 changed API. (``as_text()`` output and using ``read_bytes`` instead of ``bytes``.
* Some tests are now skipped for Python 2.7
> Fix tests due to Sphinx 3.1.1 changes

- sphinxcontrib/mat_lexer.py
- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithFunctionArguments.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
This commit adds support for function argument validation, as added in MATLAB 2019b and detailed [here](https://uk.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html).
The added test class ClassWithFunctionArguments would cause the tests to hang on the nondocumentedmethod function without the added keywords.
> Enable Function Arguments Support

- CHANGES.rst
- README.rst
- setup.py
Due to too many deprecated API's in Sphinx Docs (#118), this is the version to support Sphinx Docs version 3 and Python 2.x.
> Last version compatible with Sphinx 3 and Python 2.X

- sphinxcontrib/matlab.py
It seems like not explicitly  stating the parameter creates issues when docs are being created, as seen [here](https://github.com/ryanfox/sphinx-markdown-tables/issues/16)
> explicit parameter for paralell processing setting

- CHANGES.rst
- sphinxcontrib/mat_documenters.py
Per https://www.sphinx-doc.org/en/master/extdev/deprecated.html this has
been deprecated:
- `sphinx.ext.autodoc.members_set_option`
- The ignore argument of `sphinx.ext.autodoc.Documenter.get_doc()`
> Fix: Updated to support Sphinx >= 5

- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithBuiltinProperties.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
This PR fixes a bug that occurs if a MATLAB class has an overloaded parameter with validation functions, such as:
```matlab
classdef ClassWithBuiltinProperties < handle
% Class with properties that overload a builtin
properties
omega (1,:) {mustBeText} % a property
alpha % a property overloading a builtin
gamma (1,:) {mustBeScalarOrEmpty} % a property overloading a builtin with validation
beta (1,:) {mustBeScalarOrEmpty} % another overloaded property
end
end
```
When parsing this class `MatClass` would stop reading after reaching the first '`(`' token, following the `gamma` parameter.
I've added a fix by copying the code [that skips the function identifiers for a non-overloading parameter name](https://github.com/sphinx-contrib/matlabdomain/blob/a87837a9d6361ad171364f4a2de416ac675116ed/sph …
> Fix parsing of overloaded class parameters with validation functions

- .github/workflows/python-package.yml
- CHANGES.rst
- README.rst
- setup.py
- sphinxcontrib/mat_directives.py
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- sphinxcontrib/matlab.py
- tests/test_autodoc.py
- tests/test_docs/conf.py
- tests/test_duplicated_link.py
- tests/test_lexer.py
- tests/test_matlabify.py
- tests/test_package_links.py
- tests/test_package_prefix.py
- tests/test_parse_mfile.py
- tests/test_pymat.py
- tests/test_pymat_common_root.py
* Updated to support Pygments >= 2.14.0
* Removed imports of `future`. We only support Python 3.
* Updated tests to run on versions: "3.8", "3.9", "3.10", "3.11".
> Support Pygments >= 2.14.0

- tests/roots/test_skipping_module_members/Makefile
- tests/roots/test_skipping_module_members/conf.py
- tests/roots/test_skipping_module_members/index.rst
- tests/roots/test_skipping_module_members/make.bat
- tests/roots/test_skipping_module_members/src/first.m
- tests/roots/test_skipping_module_members/src/second.m
- tests/test_skipping_module_members.py
The project `tests/roots/test_skipping_module_members` demonstrates how to use the `'autodoc-skip-member'´ feature.
> Add a test project for skipping module members

- README.rst
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/matlab.py
- tests/roots/test_autodoc/target/ClassExample.m
- tests/test_autodoc.py
The new default is now to not show property values.
This is inline with what MathWorks does in their documentation.
Further, if the default value is `None` (i.e not set), it
is not shown anymore.
> Add new option: `matlab_show_property_default_value`

- .flake8
- sphinxcontrib/mat_directives.py
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_lexer.py
- sphinxcontrib/mat_parser.py
- sphinxcontrib/mat_types.py
- tests/test_duplicated_link.py
- tests/test_matlabify.py
- tests/test_package_links.py
- tests/test_parse_mfile.py
* All messages are prefixed with `[sphinxcontrib-matlabdomain]`.
* Use logger argument instead of build `msg` strings before.
* Started extraction of parser functionality `mat_parser.py`.
* Fixed various linter issues.
> Clean up logging messages and linter issue.

- sphinxcontrib/mat_documenters.py
- tests/test_autodoc.py
- tests/test_duplicated_link.py
- tests/test_package_links.py
Here is one approach to addressing #179.
As I looked at the code in `MatClassDocumenter.document_members()`, it occurred to me that one could still take advantage of the superclass method by "borrowing" the `exclude_members` option and calling the superclass `document_members()` multiple times with different subsets excluded.
I know this is a bit of a hack, but it does generate roughly the result I'm looking for.
What do you think of this approach?
> display class members in separate lists w/headings

- README.rst
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- sphinxcontrib/matlab.py
- tests/roots/test_autodoc/BaseClass.m
- tests/roots/test_autodoc/baseFunction.m
- tests/roots/test_autodoc/target/+package/ClassBar.m
- tests/roots/test_autodoc/target/+package/funcFoo.m
- tests/roots/test_autodoc/target/ClassExample.m
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
- tests/test_duplicated_link.py
- tests/test_package_links.py
This is preliminary work to address #178.
As stated there, currently:
- Added a `matlab_auto_link` config option that currently takes 2 options, `"see_also"` and `"all"`.
- Added a `ref_role()` method to `MatObject` types to return the role to use for references to each type of object. 
- _(now fixed)_ Need to update the regex to match only whole words. Right now if you have `myClass` and `myClassFoo`, it will replace `myClassFoo` with ``:class:`myClass`Foo``, which isn't quite what we're looking for.
> Add option `matlab_auto_link`

- CHANGES.rst
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- tests/roots/test_numad/Makefile
- tests/roots/test_numad/conf.py
- tests/roots/test_numad/index.rst
- tests/roots/test_numad/index_first.rst
- tests/roots/test_numad/index_second.rst
- tests/roots/test_numad/make.bat
- tests/roots/test_numad/readme.txt
- tests/roots/test_numad/target/FirstClass.m
- tests/roots/test_numad/target/SecondClass.m
- tests/roots/test_numad/target/readme.txt
- tests/test_numad.py
If the `:exclude-members:` options was added to a `autoclass` directive Sphinx would stop because of an exception thrown in `MatClassDocumenter:document_member_section`.
This is fixed now, as well as using the correct type the option, `sphinx.ext.autodoc.exclude_members_option`.
Fixed another issue in `MatProperty` that could not return the module it belongs to.
Added more tests, `tests/roots/test_numad`
> Fixed issue with "exclude-members" in `MatClassDocumenter`

- README.rst
- sphinxcontrib/mat_documenters.py
- tests/roots/test_autodoc/target/+package/ClassBar.m
- tests/roots/test_autodoc/target/ClassExample.m
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
I may continue to have small tweaks to the auto-link functionality as I dive into my own Matlab documentation project now, but thought I'd pass these 2 additions along now in case you want to include them in 0.20.
The new pieces are:
1. Auto-linking of property and method names in "see also" lines. That is, for a "see also" line in the docstring of a class, property or method, we can auto-link property and method names, since we know which class they belong to.
2. Property and method names in their own docstrings are also linked, mostly for the formatting, since the link isn't really very useful in that context. But it looks closer to MATLAB's output.
> two small additions to auto-link functionality

- tests/test_docs/conf.py
- tests/test_docs/index.rst
The `ClassWithStringEllipsis` could not be found, as it was in the incorrect "module".
Enabled `matlab_show_property_default_value`.
> Move item to correct location

- README.rst
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/matlab.py
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
- tests/test_numad.py
Added `matlab_class_signature` configuration. If `True` it will show the constructor arguments in the class signature.
Default is set to `False`, as this is more MATLAB-like.
See #182
> Add configuration to not show args in class signature

- sphinxcontrib/mat_types.py
This usually happens when using numpy syntax docstrings, i.e.
```
% See Also
% --------
% some text here
```
The errors looks like this:
```
File "/home/luis/.local/lib/python3.10/site-packages/sphinxcontrib/mat_documenters.py", line 206, in auto_link_see_also
entries_str = match.group(2)  # the entries
AttributeError: 'NoneType' object has no attribute 'group'
```
The fix looks like this (line 206 is new):
https://github.com/sphinx-contrib/matlabdomain/blob/f52ccbaa3e22117ebb9f4975624357db5fb37acf/sphinxcontrib/mat_documenters.py#L206-L207
> fix autolink error that occurs when "See Also" line is succeeded by "--------"

- sphinxcontrib/mat_lexer.py
- tests/test_data/f_no_input_no_parentheses_no_docstring.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
This commit adds a specific lexer for a function with outputs but no inputs (or parentheses).
Fixes #199
> Add support for function with outputs but no inputs

- sphinxcontrib/mat_documenters.py
- tests/roots/test_autodoc/target/ClassExample.m
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
Sorry, this should have been included in #201.
> Add auto-linking of fully qualified property and method names in "See also" lines.

- sphinxcontrib/mat_documenters.py
- tests/roots/test_autodoc/target/+package/ClassBar.m
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
Another minor tweak to auto-linking.
E.g. I have an `build()` method and want to include in the docstring something that says "... during the **build** phase ..." without it getting auto-linked.
> Avoid auto-linking names preceded/followed by *

- CHANGES.rst
- CITATION.bib
- sphinxcontrib/mat_types.py
- tests/roots/test_classfolder/@First/private/method_in_folder.m
We now correctly filter out `private` folders from a class folder definitions.
> Fixed #214 - private subfolders incorrectly treated as class folder.

- sphinxcontrib/mat_documenters.py
A tiny tweak to the regex that is used when auto-linking a property name in it's own docstring.
> Prevent auto-link of property name when followed by ` or *.

- CHANGES.rst
- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithSeperatedComments.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
In a situation with a comment separated by blank lines before a new comment. The parser could throw a warning.
This closes #220.
> Fix parsing of property docstring.

- sphinxcontrib/mat_types.py
Instead of having an absolute path for `matlab_src_dir` in `conf.py` interpret the supplied value as path relative to the sphinx _source_ directory. This enables the use of _matlabdomain_ with, e.g., [sphinx-multiversion](https://github.com/Holzhaus/sphinx-multiversion) which relies on running sphinx-build on different versions checked out to temporary folders. Thanks to `os.path.join()` it is still possible to provide an absolute path, though.
This solves https://github.com/Holzhaus/sphinx-multiversion/issues/108 which I found while looking for a solution.
> Interpret `matlab_src_dir` relative to the sphinx source directory.

- CITATION.bib
- setup.py
As discussed in https://github.com/sphinx-doc/sphinx/issues/11562, a new trove classifier for Sphinx domains has been added.
> Meta: Add trove classifier : `Framework :: Sphinx :: Domain`

- CHANGES.rst
- README.rst
- sphinxcontrib/mat_types.py
As mentioned in https://github.com/sphinx-contrib/matlabdomain/pull/224#issuecomment-1858919457 it should be relative to the source directory to be compatible with https://pypi.org/project/sphinx-multiversion/
> Hot-fix for `matlab_src_dir` relative path.

- CHANGES.rst
- sphinxcontrib/mat_types.py
- tests/test_data/arguments.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
For classes named with a reserved word (like arguments), we would print an incorrect warning.
> Fixed issue with incorrect warning on class names

- .github/workflows/python-package.yml
- tox.ini
External sphinxcontrib packages, have been updated to require Sphinx>=5.0
- sphinxcontrib-devhelp==1.0.2
- sphinxcontrib-applehelp==1.0.4
- sphinxcontrib-htmlhelp==2.0.1
- sphinxcontrib-serializinghtml==1.1.5
- sphinxcontrib-qthelp==1.0.3
We therefore extracted testing on Sphinx 4.5 to use the explicit versions above,
and then only test on Python 3.8 and 3.9.
Further, testing on Sphinx>=5.3 now tests on Python 3.9, 3.10, 3.11 and 3.12.
> GH Actions: Add separate job for Sphinx 4.5 

- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- sphinxcontrib/matlab.py
Please see if you think this is the correct fix for #243. I didn't get a chance to create a test specifically for this issue, but all of the existing tests pass, and it does fix the particular case I encountered.
And let me know if you need me to create a test before you merge this.
> Fix "can't link function short name if it matches module name"

- sphinxcontrib/mat_documenters.py
- sphinxcontrib/matlab.py
It does not seem to have any purpose. Modifed `MatAttributeDocumenter` to document all `MatProperty` types.
Further, the undocumented and unused directives:
* `mat:instanceattribute`
* `mat:autoinstanceattribute`
have also been removed.
This should resolve #250.
> Removed `MatInstanceAttributeDocumenter`

- .github/workflows/python-package.yml
- tests/helper.py
- tox.ini
As per https://github.com/sphinx-doc/sphinx/issues/12629 Sphinx 8 is coming out soon.
Updated testing to work with dev. version, the up-coming version 8.
> Ci: Test on Sphinx 8 / Dev.

- .github/workflows/python-package.yml
In https://github.com/sphinx-doc/sphinx/commit/541bf7bc67db3e6752383af22c8d7cc4d1eb652f they dropped support for Python < 3.11 for Sphinx.
Update the tests accordingly.
> CI: Dev. version of Sphinx requires >= Python 3.11

- .github/workflows/python-package.yml
- setup.py
- Temporary until the issue is fixed upstream or is fixed on matlabdomain side
- change cron schedule to run tests only once Mondays (to avoid bombarding CI with the same workflow for one hour everyday see https://github.com/sphinx-contrib/matlabdomain/actions/workflows/python-package.yml?query=branch%3Amaster+event%3Aschedule)
> [MAINT] pin tree-sitter-matlab<1.0.5
