sphinx-contrib/matlabdomain

- README.rst
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- sphinxcontrib/matlab.py
- tests/test_data/script_with_comment_header_3.m
- tests/test_data/script_with_comment_header_4.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
> Add autodoc for scripts with autoscript directive

- CHANGES.rst
- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithMethodsWithSpaces.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
> Fix space in method name

- .github/workflows/python-package.yml
- dev-requirements.txt
- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithGetMethod.m
- tests/test_data/ClassWithGetterSetter.m
- tests/test_docs/index.rst
- tests/test_matlabify.py
This fixes #151. Property-get/set methods were detected incorrectly.
Updated CI to run tests correctly.
> Fix issue #151

- .github/workflows/python-package.yml
- CHANGES.rst
- sphinxcontrib/mat_types.py
Add new option, `matlab_show_property_default_value`. Default is now to not
show property values. If a property value is `None`, is not shown anymore.
> Bump to version 0.16.0

- .github/workflows/python-package.yml
Run on schedule every day to catch issue with dependencies a early as possible
> Run at 06:00UTC every day.

- sphinxcontrib/mat_documenters.py
- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithPropertyValidators.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
* Fixed parsing warning reported in #167 
* Fixed use of deprecated function reported in #166
> Fix warnings

- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithTrailingCommentAfterBases.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
> Ignore comments while parsing base classes.

- CITATION.bib
Prepare for new version 0.18.0
> Bump version in citation.bib

- CHANGES.rst
- sphinxcontrib/mat_types.py
- tests/roots/test_no_matlab_src_dir/Makefile
- tests/roots/test_no_matlab_src_dir/conf.py
- tests/roots/test_no_matlab_src_dir/index.rst
- tests/roots/test_no_matlab_src_dir/make.bat
- tests/roots/test_no_matlab_src_dir/readme.txt
- tests/test_no_matlab_src_dir.py
> Fix issue if `matlab_src_dir` is not set.

- sphinxcontrib/mat_types.py
The data is constant and does not belong in any class. It makes it easier to debug, as there are fewer members.
> Moved constant data out of MATLAB Type classes.

- sphinxcontrib/mat_types.py
> fix bug when parsing mlapp files that have no description

- README.rst
- sphinxcontrib/mat_documenters.py
- tests/roots/test_autodoc/target/ClassExample.m
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
... and a few other minor auto-linking tweaks.
> Add auto-linking of fully qualified property and method names

- sphinxcontrib/mat_types.py
Added: `DiscreteState`, `Nontunable` and `PartialMatchPriority`
> Add new property attributes

- CHANGES.rst
- CITATION.bib
- README.rst
- sphinxcontrib/mat_types.py
- tests/test_autodoc.py
* Updated `readme.rst` and `changes.rst`
* Changed relative path from source dir to configuration dir.
> Prepare release 0.21.0

- sphinxcontrib/mat_documenters.py
- tests/roots/test_autodoc/target/+package/funcFoo.m
- tests/test_autodoc.py
- tests/test_autodoc_short_links.py
> Fix bug in auto-linking literal block detection

- sphinxcontrib/mat_types.py
- tests/test_data/ClassWithTests.m
- tests/test_matlabify.py
- tests/test_parse_mfile.py
Added:
- TestTags
- SharedTestFixtures
Fixes #251
> Types: Add missing class and method attributes.

- CHANGES.rst
- CITATION.bib
> Prepare for release 0.22.0

- .github/workflows/pre-commit.yml
- .github/workflows/python-package.yml
Updates:
* actions/checkout. v3 -> v4.
* actions/setup-python. v4 -> v5.
> CI: Update to latest action versions.

- README.rst
- docs/conf.py
- readthedocs.yml
> [FIX] update read the docs config

- .github/workflows/pre-commit.yml
- .github/workflows/python-package.yml
- tox.ini
- cancel previous run of workflow on a PR or on a branch when a new commit is pushed onto it
- only run CI on upstream repo
- get colored prompt in CI
> [MAINT] cancel previous CI
